  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PEM_FILE }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          
      - name: Deploy Containers
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "
            # Stop and remove all running containers
            echo 'Stopping and removing all running containers...'
            sudo docker rm -f \$(sudo docker ps -aq) 2>/dev/null || true
            
            # Remove all unused images, volumes, and networks
            echo 'Cleaning up Docker system...'
            sudo docker system prune -af
            sudo docker volume prune -f

            # Delete any existing code files from the server
            echo 'Removing non-container files and directories...'
            sudo rm -rf ~/backend ~/frontend ~/my.cnf ~/app ~/deploy_key.pem

            # Login to GitHub Container Registry
            echo '${{ secrets.IL8_CI_CD }}' | sudo docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            # Create network if it doesn't exist
            sudo docker network create my-network 2>/dev/null || true

            # Start MariaDB container with a named volume
            sudo docker run -d \
              --name db \
              --network my-network \
              -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              -e MYSQL_DATABASE=lms_db \
              -e MYSQL_ROOT_HOST='%' \
              -p 3306:3306 \
              -v db_data:/var/lib/mysql \
              --restart unless-stopped \
              mariadb:10.5 \
              --default-authentication-plugin=mysql_native_password

            # Wait for MariaDB to be healthy
            echo 'Waiting for MariaDB to be healthy...'
            timeout 300 bash -c 'while ! sudo docker exec db mysqladmin ping -h localhost -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent; do sleep 5; done'

            # Start Backend container
            sudo docker run -d \
              --name backend \
              --network my-network \
              -e DATABASE_URL=mysql+pymysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@db:3306/lms_db \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e ALGORITHM=HS256 \
              -v backend_uploads:/app/static/uploads \
              ${{ env.IMAGE_NAME_BACKEND }}:latest \
              sh -c 'python wait_for_db.py && uvicorn main:app --host 0.0.0.0 --port 8000'

            # Start Frontend container
            sudo docker run -d \
              --name frontend \
              --network my-network \
              ${{ env.IMAGE_NAME_FRONTEND }}:latest

            # Start Nginx container
            sudo docker run -d \
              --name nginx \
              --network my-network \
              -p 80:80 \
              -p 443:443 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              nginx:latest

            # Start Certbot container
            sudo docker run -d \
              --name certbot \
              -v /etc/letsencrypt:/etc/letsencrypt \
              certbot/certbot
          "

      - name: Verify Deployment
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Verifying container status..."
          ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "
            echo 'Running Containers:'
            sudo docker ps
          "

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/deploy_key.pem
